apiVersion: v1
data:
  config.yaml: |
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - '**'
    external_services:
      custom_dashboards:
        enabled: false
      grafana:
        enabled: false
      tracing:
        enabled: false
    istio_namespace: istio-system
    login_token:
      signing_key: SOMEKEYWITHRANDOm935^532fds*fggo4OSDF_dsafv243vASD90
    in_cluster: false
    kubernetes_manager_url: http://kubernetes-manager:6970
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"auth:\n  strategy: anonymous\ndeployment:\n  accessible_namespaces:\n  - '**'\nexternal_services:\n  custom_dashboards:\n    enabled: false\n  grafana:\n    enabled: false\n  tracing:\n    enabled: false\nistio_namespace: istio-system\nlogin_token:\n  signing_key: SOMEKEYWITHRANDOm935^532fds*fggo4OSDF_dsafv243vASD90\nin_cluster: false\nkubernetes_manager_url: http://kubernetes-manager:6970\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"k8s-app":"kiali-backend"},"name":"kiali-backend","namespace":"microsec-system"}}
  creationTimestamp: "2021-06-06T11:44:16Z"
  labels:
    k8s-app: kiali-backend
  name: kiali-backend
  namespace: microsec-system
  resourceVersion: "48038613"
  uid: 485f89f8-839c-4bb6-84a2-b5f74ae29784
