apiVersion: v1
data:
  CLIENT_ID: MzUwNDU1ZTktMmRkZC00OWVjLTgwNTctMTFjNzg5MmY4ODJi
  CLIENT_SECRET: ZnhkaXRSeUhWZndDU2UtU2k4Z2RMbVljd0FKay1saW8wbUh0eHlLYUp0MA==
kind: Secret
metadata:
  labels:
    app: pagerduty
  name: pagerduty
  namespace: microsec-system
type: Opaque
